### ISSUE TITLE
'STATUS_GCODE_UNUSED_WORDS'

### ISSUE THREAD

**Issue by besnik-be** [UncleRus/grbl-mega-clean-6-axis#2]
Hi, you have a bug here:
1062 -> bit_false(value_words, (bit(WORD_X) | bit(WORD_Y) | bit(WORD_Z))); // Remove axis words.

should be like this:
bit_false(value_words, (bit(WORD_X) | bit(WORD_Y) | bit(WORD_Z) | bit(WORD_A) | bit(WORD_B) | bit(WORD_C))); // Remove axis words.

**Comment by UncleRus** [comment]
Could you create a pull request?
